### ISSUE TITLE
 ipython is specified as a dependency

### ISSUE THREAD

**Issue by sethfischer** [sethfischer/sphinxcontrib-cadquery#18]
In `pyproject.toml` ipython is specified as a dependency.

This should not be required as ipython is a dependency of [cadquery](https://github.com/CadQuery/cadquery/blob/a2c1f7c4a6176ef431c1dd84170d2caebef71e8e/setup.py#L55).

In sphinxcontrib-cadquery's `pyproject.toml`:

```toml

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

Sphinx = "^5.3.0"
ipython = ">=7.31.1"
jinja2 = ">=3.0"
```
