### ISSUE TITLE
Incorrect Sphinx version used during RTD build

### ISSUE THREAD

**Issue by sethfischer** [sethfischer/sphinxcontrib-cadquery#2]
Build [19088114](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19088114/) is expected to use Sphinx 5.3.0, rather it uses Sphinx 6.1.1.

[rtd-build-19088114.txt](https://github.com/sethfischer/sphinxcontrib-cadquery/files/10356132/rtd-build-19088114.txt)

Build 19088114 uses Poetry to install dependencies with a `post_create_environment` user-defined job, in a manner [recommended by RTD](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry).

As expected `poetry install` installs Sphinx 5.3.0. This is confirmed with `poetry show sphinx` in `post_create_environment`.

However, when the following is run by RTD:

```
/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-cadquery/envs/1/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```

The output shows that Sphinx 6.1.1 is being used:

```
Running Sphinx v6.1.1
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
writing output...
⋮
```

`.readthedocs.yaml`:

```yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    nodejs: "19"
    python: "3.9"
  jobs:
    post_create_environment:
      # install Poetry
      - pip install poetry
      - poetry config virtualenvs.create false
      # install Python dependencies
      - poetry install
      - poetry show sphinx
    post_install:
      # install Node.js dependencies
      - npm clean-install
      # build
      - npm run build

sphinx:
  configuration: docs/conf.py
```

**Comment by sethfischer** [comment]
readthedocs/readthedocs.org/issues/9869

**Comment by sethfischer** [comment]
Moving `poetry install` from `build.jobs.post_create_environment` to `post_install` resolved the issue.

[Build #19097755 ](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19097755/)

```yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    nodejs: "19"
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
      - npm clean-install
      - make npm-build

sphinx:
  configuration: docs/conf.py
```
